### NumPy Full Course

NumPy stands for Numerical Python. It is a Python library mainly used for working with numbers, arrays, mathematical calculations, and data efficiently.

The main object in NumPy is called an array. An array is a collection of values stored together.

NumPy arrays are especially useful for:

Mathematical calculations

Large amounts of numerical data

Data analysis

Machine learning

Scientific computing

### Creating a 1D Array

1D means one-dimensional.

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a)

[10 20 30 40 50]


### Creating a 2D Array

2D means rows and columns.

In [2]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(a)

[[10 20 30]
 [40 50 60]]


### Creating a 3D Array

A 3D array contains multiple 2D arrays.

In [3]:
a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Check Dimensions — ndim

ndim tells us how many dimensions an array has.

In [4]:
a = np.array([10, 20, 30])

print(a.ndim)

1


In [5]:
a = np.array([
    [10, 20],
    [30, 40]
])

print(a.ndim)

2


### Shape

shape tells us the number of rows and columns.

In [6]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(a.shape)

(2, 3)


### Size

size tells us the total number of elements.

In [7]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(a.size)

6


### Data Type — dtype

dtype tells us the type of values stored in the array.

In [8]:
a = np.array([10, 20, 30])

print(a.dtype)

int64


In [9]:
a = np.array([10.5, 20.5, 30.5])

print(a.dtype)

float64


### Indexing

NumPy indexing starts from 0.

In [10]:
a = np.array([10, 20, 30, 40])

print(a[0])
print(a[1])
print(a[2])

10
20
30


### Negative Indexing

You can access values from the end.

In [11]:
a = np.array([10, 20, 30, 40])

print(a[-1])

40


### Slicing

Slicing selects a range of values.

In [12]:
a = np.array([10, 20, 30, 40, 50])

print(a[1:4])

[20 30 40]


### 2D Array Indexing

In [13]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

### Creating Arrays with Zeros

np.zeros() creates an array filled with zeros.


In [14]:
a = np.zeros(5)

print(a)

[0. 0. 0. 0. 0.]


In [15]:
a = np.zeros((2, 3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


### Creating Arrays with Ones

In [16]:
a = np.ones(5)

print(a)

[1. 1. 1. 1. 1.]


In [17]:
a = np.ones((2, 3))

print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


### arange()

np.arange() creates numbers within a range.

In [18]:
a = np.arange(1, 10)

print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
a = np.arange(1, 10, 2)

print(a)

[1 3 5 7 9]


### linspace()

linspace() creates a specified number of equally spaced values.

In [21]:
a = np.linspace(0, 10, 5)

print(a)

[ 0.   2.5  5.   7.5 10. ]


### Identity Matrix

np.eye() creates an identity matrix.

In [22]:
a = np.eye(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random Numbers

NumPy can generate random numbers.

In [23]:
a = np.random.rand(5)

print(a)

[0.58841615 0.98571672 0.93028764 0.53571503 0.97522335]


In [24]:
a = np.random.randint(1, 10, 5)

print(a)

[9 8 1 6 3]


### Arithmetic Operations

One major advantage of NumPy is that we can perform calculations directly on arrays.

In [25]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [26]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


### Mathematical Operation

In [27]:
a = np.array([10, 20, 30, 40]) #sum

print(np.sum(a))

100


In [28]:
print(np.mean(a))  #mean

25.0


In [29]:
print(np.max(a)) # maximum

40


In [30]:
print(np.min(a)) # minimum

10


In [31]:
print(np.std(a))  #standard deviation

11.180339887498949


### Sorting

In [32]:
a = np.array([40, 10, 30, 20])

print(np.sort(a))

[10 20 30 40]


### Reshape

reshape() changes the shape of an array without changing its values.

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])

### Flatten

flatten() converts a multidimensional array into one dimension.

In [34]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = a.flatten()

print(b)

[1 2 3 4 5 6]


### Concatenate Arrays

concatenate() joins arrays.

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c)

[1 2 3 4 5 6]


### Stack Arrays

vstack() joins arrays vertically.

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


### Filtering NumPy Arrays

This is similar to filtering a Pandas DataFrame.

In [37]:
a = np.array([10, 20, 30, 40, 50])

print(a[a > 25])

[30 40 50]
